# Generated by Django 5.0.4 on 2024-05-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="objective",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="objective",
            name="course",
        ),
        migrations.CreateModel(
            name="CourseObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.course",
                    ),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.objective",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "objective")},
            },
        ),
    ]
