# Generated by Django 5.0.4 on 2024-04-26 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0002_alter_evaluation_levela_stu_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="degree",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="university.degree",
            ),
        ),
    ]
