# Generated by Django 5.0.4 on 2024-04-26 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0003_section_degree"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="section",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="levelA_stu_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="levelB_stu_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="levelC_stu_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="levelF_stu_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="degree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="university.degree",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("course", "section_id", "semester", "year", "degree")},
        ),
    ]
