# Generated by Django 5.0.4 on 2024-05-01 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0005_evaluation_improvement_needed_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="objective",
            unique_together={("course", "objective_code")},
        ),
    ]
