# Generated by Django 5.0.4 on 2024-05-01 01:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0006_alter_objective_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("course", "section_id", "semester", "year")},
        ),
        migrations.RemoveField(
            model_name="section",
            name="degree",
        ),
    ]
